services:
  app:
    image: laravelphp/php:8.3-fpm
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inner
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network
    restart: always  
    
volumes:
  mysql_data: 

networks:
  laravel-network: